### ISSUE TITLE
Question: How doe this improve on your older design?

### ISSUE THREAD

**Issue by JohnOCFII** [x0pherl/fender-bender#2]
I've been using your previous design successfully since 2021.  I'd love to hear how this differs.  I really like unit I'm using but have considered a change for three reasons:

1) Filament seems to break when sitting for more than a week.  This might be unavoidable due to the way the filament is positioned as it flows through the buffer.

2) Occasionally I struggle to get the filament to exit the unit as it gets caught on the M10, and I have to twist it quite a bit to get it to flow smoothly through the opening.

3) I'd like to try to better seal the box, as I've found that I get much better prints when my filament is dry, and while I'm starting from a sealed/dry RepBox, the current solution is out in the open.  I guess I can go with the sealed walls as a start.

Thanks!

**Comment by x0pherl** [comment]
hey, nice to know the previous design was working for you. i'll address your issues and talk about general improvements.

1. that's a factor of the PTFE tubes, filament gets brittle in the tubes. i've seen this discussed enough to consider it "generally known" although google might reveal reasons. the "standard version" of this new design uses 3mm ID, 6mm OD tubing; I'm curious to see if this helps with that problem, but i haven't been using it long enough to know yet.
2. this design uses no connectors on the buffer, or alternative bottom brackets use "pass through connectors". In either of these cases, the path of the filament through the connector (and even through the part) is lined, which eliminates the catching you describe (and also greatly reduces overall friction. this was a design goal for this project)
3. There's already an [issue ](https://github.com/x0pherl/fender-bender/issues/1) opened for a sealed version; this will mostly require some redesign of the bottom part but it should be pretty easy, but it will be a while before I get to it. But thanks for weighing in, I definitely am interested in what folks are looking for, and this seems to be a common request in early feedback.

Other improvements:
- the path of the filament now exits the buffer at a 45 degree angle. installing such that there's a straight path to your filament and a straight path to the MMU has cut friction more than 4x vs. the design you're using (in fact my first attempt did that so effectively that it pushed the filament right around the wheel and back into my repbox)
- the "bracket" no longer has those awful printed screws, it just snaps into place. this makes me happy every time I assemble one (but doesn't impact daily operation).
- you could achieve this without printing a whole new buffer, but the PTFE stepdown adapter design makes the path from the buffer to the printer more easily user serviced. this makes loading filament way easier.
- the 6mm OD tubing is significantly more durable than 4mm tubing. it makes it a little "stiffer" when changing filament, but should mean better performance and durability over time.
- the new design is much easier to tinker with than the old one, which should allow for more variants in the future (such as a drybox config or different entry / exit angles, etc (this may not be enough to merit an upgrade at this time -- see more below -- but is a definite improvement).
- there are 3 different "locking mechanisms" for the new design -- they simply "snap" into place with a click lock point, which has worked well enough for me without further locking. but there's also a per-bracket sliding pin (as before) or a pin that slides in from the side. if the click lock holds up over time then this will make changing filament easier.
- the top and bottom of the buffer now can mount to the wall, which will allow for 2 connection points on the same stud.

generally if you have something in place that's working for you, you may want to hang on for a bit and see what comes down the pike as folks raise issues or feature requests and I address them ¯\_(ツ)_/¯

I will say that if you have spare cycles on your printer and you're willing to burn through the filament to test this model, I would greatly appreciate your perspective as someone who used the previous version. However, I would still probably recommend that you wait for solid walls and a sealed bottom before testing. That's also likely to give me some time to address some other minor concerns. I'll be populating issues after Printopia weekend which should give you an idea of what's coming.
